# -*- coding: utf-8 -*-
"""ConditionalAsnmnt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnU3k7bG4e30Pn3l-8q69aVQpO88QId_
"""

student_name=input("enter name")
a=int(input("enter maths marks"))
b=int(input("enter science marks"))
c=int(input("enter english marks"))

if a<0 or a>100 or b<0 or b>100 or c<0 or c>100:
  print("Invalid marks entered")
  exit()

else:
  total_marks=a+b+c
  avg_per=total_marks/3

  print(f"Student Name: {student_name}")
  print(f"Total Marks: {total_marks}")
  print(f"Percentage: {round(avg_per,2)}")
  if a<40 or b<40 or c<40:
     print(f"Status: Fail")
  else:
     print(f"Status: Pass")
     if avg_per>=75:
        print(f"Grade: A")
     elif avg_per>=60 and avg_per<75:
        print(f"Grade: B")
     elif avg_per>=40 and avg_per<60:
        print(f"Grade: C")