# -*- coding: utf-8 -*-
"""game_score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnU3k7bG4e30Pn3l-8q69aVQpO88QId_
"""

player_name=input("enter player name")
no_of_games=int(input("enter number of games played"))
total_score=int(input("enter score"))
average_score=total_score/no_of_games

print(f"Player: {player_name}")
print(f"Games Played: {no_of_games}")
print(f"Total Score: {total_score}")
print(f"Average Score: {average_score}")